on: push
name: CI
jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master

    - name: test
      run: ls -la /home/runner/work/github-actions/github-actions/ci/actions/lint_md
    
    - name: lint_md
      uses: ./.github/actions/lint_md
      env:
        MESSAGE: Hello World
    
    - name: build
      uses: ./.github/actions/build/
    
    - name: deploy
      uses: ./.github/actions/deploy/
