on: push
name: Main Workflow
jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    
    - name: lint_md
      uses: .github/actions/lint_md/
      env:
        MESSAGE: Hello World
    
    - name: build
      uses: .github/actions/build/
    
    - name: deploy
      uses: .github/actions/deploy/
